name: reactive_dart
description: An implementation of the observer pattern on sequences.
version: 0.0.1
author: John Evans <prujohn@gmail.com>
homepage: https://github.com/prujohn/Reactive-Dart
dependencies:
  unittest:
    sdk: unittest